name: nsv
on:
  push:
    branches:
      - main

jobs:
  nsv:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_NSV }}

      - name: Capture CI Variables
        run: |
          env | sort > github_env

      - name: Tag
        uses: dagger/dagger-for-github@v7
        env:
          # skipcq: SCT-A000
          GPG_PRIVATE_KEY: "${{ secrets.GPG_PRIVATE_KEY }}"
          GPG_PASSPHRASE: "${{ secrets.GPG_PASSPHRASE }}"
        with:
          verb: call
          module: github.com/purpleclay/daggerverse/nsv@v0.11.1
          args: --src . --dotenv github_env patch --hook scripts/patch.sh --show --gpg-private-key env:GPG_PRIVATE_KEY --gpg-passphrase env:GPG_PASSPHRASE
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
