name: patch
on:
  push:
    tags:
      - "*.*.*"

jobs:
  patch:
    runs-on: ubuntu-24.04
    steps:
      - name: Git Clone
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.repository.default_branch }}

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          trust_level: 5
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_config_global: true

      - name: Strip Tag Prefix
        id: strip_tag
        run: |
          TAG=${GITHUB_REF##*/}
          STRIPPED_TAG=${TAG#v}
          echo "tag=${STRIPPED_TAG}" >> $GITHUB_OUTPUT

      - name: Patch Version
        run: |
          echo "${{ steps.strip_tag.outputs.tag }}" > VERSION

      - name: Print Git Config
        run: |
          git config --global --list

      - name: Commit Changes
        run: |
          git add VERSION
          git commit -S -m "chore(deps): bump version to ${{ steps.strip_tag.outputs.tag }} [skip ci]"
          git push
